### ISSUE TITLE
Size/Visibility of Menu Bar

### ISSUE THREAD

**Issue by kholuba** [elotroalex/frontlines#18]
The Menu bar in the top right corner seems a little too small/tough to see. Especially when you first land on the Ebola page- it gets hidden in the picture. I know it travels down with you as you scroll, but I feel like it could be improved a little bit. 

1. I think we should definitely increase the size of "Menu" so that it is a little more noticeable
2. Maybe cut down the frame of the picture on the Ebola page so that the menu is noticeable when you land 
3. Maybe consider changing the color of the font of the "Menu"

These are all just suggestions (except #1 in my opinion). I like to use the Menu bar to navigate around the site so I think it needs to stand out a little more.

**Comment by elotroalex** [comment]
I agree with you, but that was a part of their design, and became one of
the elements that made it into the final version. We can't change the font
to lighter because then it would become invisible in the rest of the page.
The loss is not that big, since it's just one page and it's only on laptop
view for the top.

**Comment by elotroalex** [comment]
Ok, I think this is fixed. At least those parts that don't diverge too much from the design.
